CREATE TABLE `profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`application_id` text NOT NULL,
	`details` text,
	`state` text,
	`large_image_key` text,
	`large_image_text` text,
	`small_image_key` text,
	`small_image_text` text,
	`button1_label` text,
	`button1_url` text,
	`button2_label` text,
	`button2_url` text,
	`party_size` integer,
	`party_max` integer,
	`show_elapsed_time` integer DEFAULT false NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
