import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'

export const profiles = sqliteTable('profiles', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  applicationId: text('application_id').notNull(),
  activityType: integer('activity_type').notNull().default(0),
  details: text('details'),
  detailsUrl: text('details_url'),
  state: text('state'),
  stateUrl: text('state_url'),
  streamUrl: text('stream_url'),
  largeImageKey: text('large_image_key'),
  largeImageText: text('large_image_text'),
  largeImageUrl: text('large_image_url'),
  smallImageKey: text('small_image_key'),
  smallImageText: text('small_image_text'),
  smallImageUrl: text('small_image_url'),
  button1Label: text('button1_label'),
  button1Url: text('button1_url'),
  button2Label: text('button2_label'),
  button2Url: text('button2_url'),
  partySize: integer('party_size'),
  partyMax: integer('party_max'),
  timestampMode: integer('timestamp_mode').notNull().default(0),
  startTimestamp: integer('start_timestamp'),
  endTimestamp: integer('end_timestamp'),
  showElapsedTime: integer('show_elapsed_time', { mode: 'boolean' }).notNull().default(false),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull()
})
